FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*"}

[Project]
Name = "CellarId"
TargetType = "BeefGUIApplication"
StartupObject = "CellarId.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "$(ProjectName)_d"
DebugWorkingDirectory = "$(ProjectDir)\\dist"
